version: '3.8'

services:
  app:
    image: python:3.12-slim
    container_name: flask_app
    working_dir: /app
    volumes:
      - ..:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: >
       sh -c "pip install --no-cache-dir -r /app/requirements.txt && python /app/app/app.py"
    restart: always

#docker compose -f docker/docker-compose.yml up -d